config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages
  resources :social_media
  resources :home_page_blocks
  resources :image_slides
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'homes#index'
get 'contact-us', to: 'contact_messages#new', as: 'new_message'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
	attr_accessor :name, :email, :message
  validates :name, :email, :message, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/home_page_block.rb
class HomePageBlock < ApplicationRecord
	has_one_attached :image
	
end

app/models/image_slide.rb
class ImageSlide < ApplicationRecord
	has_one_attached :image
	def index
		@imageSlide = ImageSlide.all
	end
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :image
end

app/models/social_media.rb
class SocialMedia < ApplicationRecord
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :description)
    end
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < InheritedResources::Base

  private

    def contact_message_params
      params.require(:contact_message).permit(:name, :email, :message)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/image_slides_controller.rb
class ImageSlidesController < InheritedResources::Base

  private

    def image_slide_params
      params.require(:image_slide).permit(:title, :body,:image)
    end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

  private

    def page_params
      params.require(:page).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def brand_name
	@name_of_brand ||= "Nerd Gang"	
	end

	def site_title
		@site_name ||= "::..Nerd Gang..:: When it comes to code we do our own stunts"
	end
	
	def footer
		"© #{brand_name} 2018." + ' ' + 'All Rights Reserved.'
	end

	def designed_by
		@sly_talk ||= "Another Digital hit by: "
		@sly_talk + "#{brand_name}"
	end

	def my_slider
		@imageSlide = ImageSlide.all
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/helpers/home_page_blocks_helper.rb
module HomePageBlocksHelper

	def my_blocks
		homepage_block = HomePageBlock.all
		
	end

	def setup_the_homepage_blocks(homepage_block_array,block_item)
		homepage_block_index = homepage_block_array.index(block_item)

		homepage_block_index % 2 == 0
		
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/image_slides_helper.rb
module ImageSlidesHelper
	def image_slider
		@image_slides = ImageSlide.all
	end

	def set_active_slide(slides)
slides.first
		
	end

	def setup_the_slides(slide_array,slide)
		slide_index = slide_array.index(slide)

		slide_index == 0
		
	end
end

app/helpers/pages_helper.rb
module PagesHelper
	def pages
		@pages = Page.all
		
	end
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/views/contact_messages/_form.html.erb
<div class="container">
  <%= form_with(model: contact_message, local: true) do |form| %>
  <% if contact_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_message.errors.count, "error") %> prohibited this contact_message from being saved:</h2>

      <ul>
      <% contact_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit 'Send', class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/contact_messages/edit.html.erb
<h1>Editing Contact Message</h1>

<%= render 'form', contact_message: @contact_message %>

<%= link_to 'Show', @contact_message %> |
<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row content_blocks">
    <h1 class="text-center">Contact Messages</h1>
  </div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_messages.each do |contact_message| %>
      <tr>
        <td><%= contact_message.name %></td>
        <td><%= contact_message.email %></td>
        <td><%= contact_message.message %></td>
        <td><%= link_to 'Show', contact_message %></td>
        <td><%= link_to 'Edit', edit_contact_message_path(contact_message) %></td>
        <td><%= link_to 'Destroy', contact_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Message', new_contact_message_path %>

</div>

app/views/contact_messages/new.html.erb
<div class="container content_blocks">
	<h1 class="spacer_bottom">New Contact Message</h1>
</div>

<%= render 'form', contact_message: @contact_message %>

<%= link_to 'Back', ("/") %>

app/views/contact_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact_message.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_message.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_message.message %>
</p>


<%= link_to 'Back', ("/") %>