config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages
  resources :social_media
  resources :home_page_blocks
  resources :image_slides
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'homes#index'
get 'contact-us', to: 'contact_messages#new', as: 'new_message'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
	attr_accessor :name, :email, :message
  validates :name, :email, :message, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/home_page_block.rb
class HomePageBlock < ApplicationRecord
	has_one_attached :image
	
end

app/models/image_slide.rb
class ImageSlide < ApplicationRecord
	has_one_attached :image
	def index
		@imageSlide = ImageSlide.all
	end
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :image
end

app/models/social_media.rb
class SocialMedia < ApplicationRecord
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :description)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/image_slides_controller.rb
class ImageSlidesController < InheritedResources::Base

  private

    def image_slide_params
      params.require(:image_slide).permit(:title, :body,:image)
    end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

  private

    def page_params
      params.require(:page).permit(:title, :body)
    end
end

app/controllers/social_media_controller.rb
class SocialMediaController < InheritedResources::Base

  private

    def social_medium_params
      params.require(:social_medium).permit(:title, :link, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def brand_name
	@name_of_brand ||= "Nerd Gang"	
	end

	def site_title
		@site_name ||= "::..Nerd Gang..:: When it comes to code we do our own stunts"
	end
	
	def footer
		"© #{brand_name} 2018." + ' ' + 'All Rights Reserved.'
	end

	def designed_by
		@sly_talk ||= "Another Digital hit by: "
		@sly_talk + "#{brand_name}"
	end

	def my_slider
		@imageSlide = ImageSlide.all
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/helpers/home_page_blocks_helper.rb
module HomePageBlocksHelper

	def my_blocks
		homepage_block = HomePageBlock.all
		
	end

	def setup_the_homepage_blocks(homepage_block_array,block_item)
		homepage_block_index = homepage_block_array.index(block_item)

		homepage_block_index % 2 == 0
		
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/image_slides_helper.rb
module ImageSlidesHelper
	def image_slider
		@image_slides = ImageSlide.all
	end

	def set_active_slide(slides)
slides.first
		
	end

	def setup_the_slides(slide_array,slide)
		slide_index = slide_array.index(slide)

		slide_index == 0
		
	end
end

app/helpers/pages_helper.rb
module PagesHelper
	def pages
		@pages = Page.all
		
	end
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.description %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @client.description %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<%= render 'layouts/home' %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/image_slides/_form.html.erb
<%= form_with(model: image_slide, local: true) do |form| %>
  <% if image_slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_slide.errors.count, "error") %> prohibited this image_slide from being saved:</h2>

      <ul>
      <% image_slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/image_slides/edit.html.erb
<h1>Editing Image Slide</h1>

<%= render 'form', image_slide: @image_slide %>

<%= link_to 'Show', @image_slide %> |
<%= link_to 'Back', image_slides_path %>

app/views/image_slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Slides</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_slides.each do |image_slide| %>
      <tr>
        <td><%= image_slide.title %></td>
        <td><%= image_slide.body %></td>
        <td><%= link_to 'Show', image_slide %></td>
        <td><%= link_to 'Edit', edit_image_slide_path(image_slide) %></td>
        <td><%= link_to 'Destroy', image_slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Slide', new_image_slide_path %>

app/views/image_slides/new.html.erb
<h1>New Image Slide</h1>

<%= render 'form', image_slide: @image_slide %>

<%= link_to 'Back', image_slides_path %>

app/views/image_slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image_slide.title %>
</p>

<div>
	<%=image_tag(@image_slide.image)%>
</div>

<p>
  <strong>Body:</strong>
  <%= @image_slide.body %>
</p>

<%= link_to 'Edit', edit_image_slide_path(@image_slide) %> |
<%= link_to 'Back', image_slides_path %>

app/views/social_media/_form.html.erb
<%= form_with(model: social_medium, local: true) do |form| %>
  <% if social_medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(social_medium.errors.count, "error") %> prohibited this social_medium from being saved:</h2>

      <ul>
      <% social_medium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/social_media/edit.html.erb
<h1>Editing Social Medium</h1>

<%= render 'form', social_medium: @social_medium %>

<%= link_to 'Show', @social_medium %> |
<%= link_to 'Back', social_media_path %>

app/views/social_media/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Social Media</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_media.each do |social_medium| %>
      <tr>
        <td><%= social_medium.title %></td>
        <td><%= social_medium.link %></td>
        <td><%= link_to 'Show', social_medium %></td>
        <td><%= link_to 'Edit', edit_social_medium_path(social_medium) %></td>
        <td><%= link_to 'Destroy', social_medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social Medium', new_social_medium_path %>

app/views/social_media/new.html.erb
<h1>New Social Medium</h1>

<%= render 'form', social_medium: @social_medium %>

<%= link_to 'Back', social_media_path %>

app/views/social_media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @social_medium.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @social_medium.link %>
</p>

<%= link_to 'Edit', edit_social_medium_path(@social_medium) %> |
<%= link_to 'Back', social_media_path %>