config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages
  resources :social_media
  resources :home_page_blocks
  resources :image_slides
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'homes#index'
get 'contact-us', to: 'contact_messages#new', as: 'new_message'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
	attr_accessor :name, :email, :message
  validates :name, :email, :message, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/home_page_block.rb
class HomePageBlock < ApplicationRecord
	has_one_attached :image
	
end

app/models/image_slide.rb
class ImageSlide < ApplicationRecord
	has_one_attached :image
	def index
		@imageSlide = ImageSlide.all
	end
end

app/models/page.rb
class Page < ApplicationRecord
	has_one_attached :image
end

app/models/social_media.rb
class SocialMedia < ApplicationRecord
	has_one_attached :image
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :description)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

  private

    def page_params
      params.require(:page).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def brand_name
	@name_of_brand ||= "Nerd Gang"	
	end

	def site_title
		@site_name ||= "::..Nerd Gang..:: When it comes to code we do our own stunts"
	end
	
	def footer
		"© #{brand_name} 2018." + ' ' + 'All Rights Reserved.'
	end

	def designed_by
		@sly_talk ||= "Another Digital hit by: "
		@sly_talk + "#{brand_name}"
	end

	def my_slider
		@imageSlide = ImageSlide.all
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/helpers/home_page_blocks_helper.rb
module HomePageBlocksHelper

	def my_blocks
		homepage_block = HomePageBlock.all
		
	end

	def setup_the_homepage_blocks(homepage_block_array,block_item)
		homepage_block_index = homepage_block_array.index(block_item)

		homepage_block_index % 2 == 0
		
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/image_slides_helper.rb
module ImageSlidesHelper
	def image_slider
		@image_slides = ImageSlide.all
	end

	def set_active_slide(slides)
slides.first
		
	end

	def setup_the_slides(slide_array,slide)
		slide_index = slide_array.index(slide)

		slide_index == 0
		
	end
end

app/helpers/pages_helper.rb
module PagesHelper
	def pages
		@pages = Page.all
		
	end
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/views/layouts/_carousel.html.erb
<div class="col-sm-8">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        
        <% if !my_slider.blank? %>
        <%i=0%>
          <% for item in my_slider %>
          <%if setup_the_slides(my_slider,item)%>
          <li data-target="#myCarousel" data-slide-to="<%=i%>" class="active"></li>
          <%else%>
          <li data-target="#myCarousel" data-slide-to="<%=i%>"></li>
          <%end%>
            
          <% end %>
        <% else %>
          
        <% end %>
        
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox"> 
        <% if !my_slider.blank? %>
        
        <% for slideritem in my_slider %>

<%if setup_the_slides(my_slider,slideritem)%>
<div class="item active col-md-12 mx-auto" style="width: 800px; height: 400px">
          <%=image_tag(slideritem.image,style:'width:100%')%>
          <div class="carousel-caption">
            <h3><%= slideritem.title %></h3>
            <p><%= slideritem.body %></p>
          </div>      
        </div>
<%else%>
<div class="item col-md-12" style="width: 800px; height: 400px">
          <%=image_tag(slideritem.image,style:'width:100%')%>
          <div class="carousel-caption">
            <h3><%= slideritem.title %></h3>
            <p><%= slideritem.body %></p>
          </div>      
        </div>
        <% end %> 
      <% end %>
      </div>
<%end%>

      </div>
      

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
  <p><%= footer %></p>
  <p id="design_by"><%= designed_by %></p>
</footer>

app/views/layouts/_form.html.haml
= semantic_form_for [:admin, @slide], builder: ActiveAdmin::FormBuilder do |f|
  = f.inputs do
    = f.input :title
    = f.input :body
    = f.input :image, as: :file
    = f.actions

app/views/layouts/_header.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    
    .carousel-inner img {
      width: 100%; /* Set width to 100% */
      min-height: 200px;
    }

    /* Hide the carousel text when the screen is less than 600 pixels wide */
    @media (max-width: 600px) {
      .carousel-caption {
        display: none; 
      }
    }
  </style>
</head>

<nav class="navbar navbar-inverse_ng">
  <div class="container-fluid">
    <div id="brand_nav" class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a id="brand_name" class="navbar-brand" href="/"><%=brand_name%></a>
    </div>
    <div id="nav_items" class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <% if !pages.blank? %>
          <% for page in pages %>
            <li><a href="/pages/<%=page.id%>"><%=page.title%></a></li>
          <% end %>
        <% else %>
          
        <% end %>
        <li><a href="mailto:haveyec@me.com?subject=Message From NG Contact Form&body=Hi Nerd Gang,
        My name is:
        I'm looking to get:">Contact Us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="admin"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_home.html.erb
<div class="container">
<div class="row">
  <%= render 'layouts/carousel' %>
  <div class="col-sm-4">
    <div>
      <%=image_tag("ngLogo.jpg", size: "350x350")%>
    </div>
  </div>
</div>
<hr>
</div>


<%=render 'layouts/homepageblock' %>

<div id="digital_agency" class="container spacer_bottom spacer_top"><div class="row"><section class="col-lg-5 bg_color"><h1 class="text-center">Not just a digital agency</h1>
<h3 class="text-center">WE ARE DIGITAL EXPERTS</h3>
<p class="homepageP">
We work with clients big and small across a range of sectors and we utilise all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you to fully understand your business to achieve the greatest amount of publicity possible so that you can see a return from the advertising.</p>
</section>

<section class="col-lg-2"></section>

<section id="digital_marketing" class="col-lg-5 text-center"><h1>WE CONNECT BRANDS</h1><h3>We're an independent creative agency</h3><p>We're a small, but mighty marketing agency that produces effective work for great clients through creativity, agility, ingenuity, and dialed-in strategy.</p> 

<p>With an itch for greatness in everything we do, we create, design and tell stories with a persistent commitment to innovation and efficiency. Our pursuit of excellence is the only way we know how to generate ideas that stick and that accelerate your brand's progress.</p>
</section>
</div>
</div>

<div class="container spacer_bottom"><div class="row"><section class="section-call-to-action action-center action-lg bg-gray m-t-40">
        <div class="action-wrapper animated" data-animation="fadeInUp" data-animation-delay="600">
          <div class="action-text">
            <h2 class="action-title text-center brand_color">Ready to create your new awesome project with the Gang?</h2>
          </div>
          <div class="action-btn m-t-40">
            <div id="contact" class="container text-center"><a href="contact-us" class="btn btn-primary text-center btn-lg"><i class="nc-icon-outline ui-1_email-85"></i><span>Contact us</span></a></div>
          </div>
        </div>
      </section></div></div>

<div id="products_section" class="container">
	<div class="row products">

            <div class="col-lg-12">
                <h2 class="page-header">Our Products</h2>
            </div>
		
			<div class="col-sm-4 col-lg-3 col-md-4">
				<div class="thumbnail">
					<img src="https://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$24.99</h4>
						<h4><a href="#">First Product</a></h4>
						<p>This product is cheap, and has a very good quality. You must buy it right now!</p>
					</div>
					<div class="ratings">
						<p class="pull-right">15 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-3 col-md-4">
				<div class="thumbnail">
					<img src="https://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$64.99</h4>
						<h4><a href="#">Second Product</a></h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">12 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-3 col-md-4">
				<div class="thumbnail">
					<img src="https://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$74.99</h4>
						<h4><a href="#">Third Product</a></h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">31 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-3 col-md-4">
				<div class="thumbnail">
					<img src="https://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$84.99</h4>
						<h4><a href="#">Fourth Product</a></h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">6 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-3 col-md-4">
				<div class="thumbnail">
					<img src="https://placehold.it/320x150" alt="">
					<div class="caption">
						<h4 class="pull-right">$94.99</h4>
						<h4><a href="#">Fifth Product</a></h4>
						<p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					</div>
					<div class="ratings">
						<p class="pull-right">18 reviews</p>
						<p>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star"></span>
							<span class="glyphicon glyphicon-star-empty"></span>
						</p>
					</div>
				</div>
			</div>

			<div class="col-sm-4 col-lg-3 col-md-4">
				<h4><a href="#">Like our products?</a></h4>
				<p>Pick your products today to get free shipping!</p>
				<a class="btn btn-primary" target="_blank" href="#">Let's go!</a>
			</div>

		</div>	</div>

<div class="container text-center spacer_bottom">    
  <h3 class="homepage_header section_header">BRANDS THAT PUT THEIR TRUST IN US.</h3>
  <br>
  <div class="row">
    <div class="col-sm-2"> 
      <img src="https://vignette.wikia.nocookie.net/logopedia/images/6/62/NICKELODEON_Logo.png/revision/latest?cb=20111106061132&format=original" class="img-responsive" style="width:100%" alt="Image">
      <p></p>
    </div> 
    <div class="col-sm-2">
      <img src="https://vignette.wikia.nocookie.net/logopedia/images/3/3a/Bet-520x245.png/revision/latest?cb=20140815150429" class="img-responsive" style="width:100%" alt="Image">
      <p></p>
    </div>
    <div class="col-sm-2"> 
      <img src="http://images4.fanpop.com/image/photos/21700000/Disney-walt-disney-50-animated-motion-pictures-21757269-1724-796.png" class="img-responsive" style="width:100%" alt="Image">
      <p></p>
    </div>
    <div class="col-sm-2"> 
      <img src="https://vignette.wikia.nocookie.net/90scartoons/images/b/bc/Mtv-logo-Logo.png/revision/latest?cb=20140219002555" class="img-responsive" style="width:100%" alt="Image">
      <p></p>
    </div> 
    <div class="col-sm-2"> 
      <img src="https://upload.wikimedia.org/wikipedia/commons/6/65/Comedy_Central_Logo_2011_vertikal.png" class="img-responsive" style="width:100%" alt="Image">
      <p></p>
    </div>     
    <div class="col-sm-2"> 
      <img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Logo_VH1_IT.png" class="img-responsive" style="width:100%" alt="Image">
      <p></p>
    </div> 
  </div>
</div><br>

app/views/layouts/_homepageblock.html.erb
<% if !my_blocks.blank? %>
	<% for my_block_item in my_blocks %>
	<%if setup_the_homepage_blocks(my_blocks,my_block_item) %>
	<div class="container text-center spacer_top spacer_bottom"> 

  <div class="row">

<section class="col-lg-6 mainServicesSections content_blocks"><h1 class="text-center"><%=my_block_item.title%></h1>

    <p class="text-center"><%=raw my_block_item.body%></p>

<a href="/home_page_blocks/<%=my_block_item.id%>" class="btn btn-primary btn-lg"><%=my_block_item.button_title%></a>
</section>

  <section class="col-lg-6"><%=image_tag(my_block_item.image, size: "450x450")%></section></div>
</div>

	<%else%>

		<div class="container text-center">

<div class="row"><section class="col-lg-6"><%=image_tag(my_block_item.image, size: "450x450")%></section>

<section class="col-lg-6 content_blocks"><h1 class="text-center"><%=my_block_item.title%></h1> 
	<p class="text-center"><%=raw my_block_item.body%></p>

<div class="text-center mainServicesSections"><a href="/home_page_blocks/<%=my_block_item.id%>" class="btn btn-primary btn-lg"><%=my_block_item.button_title%></a></div>
</section></div>
</div>
	<% end %>
<% end %>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= site_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/header'%>
    <%= yield %>
    <%=render 'layouts/footer'%>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.body %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="row content_blocks">
		<h1 class="text-center">
  
  <%=raw @page.title %>
</h1>

	</div>
	<div class="row content_blocks">
		<p class="text-center">
  
  <%=raw @page.body %>
</p>
	</div>
</div>